# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('registration_date', models.DateField(null=True)),
                ('person_type', models.CharField(max_length=15, null=True)),
                ('prefix', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('house_number', models.CharField(max_length=10, null=True)),
                ('house_name', models.CharField(max_length=30, null=True)),
                ('land_mark', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
                ('donation_frequency', models.CharField(max_length=15, null=True)),
                ('current_status', models.CharField(max_length=10, null=True)),
                ('mode_of_communication', models.CharField(max_length=10, null=True)),
                ('payment_mode', models.CharField(max_length=10, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
