# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0004_auto_20171112_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('payment_mode_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('payment_mode_desc', models.CharField(max_length=100, null=True)),
                ('payment_mode_remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('purpose_desc', models.CharField(max_length=100, null=True)),
                ('purpose_remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(null=True)),
                ('Receipt_number', models.CharField(max_length=5, null=True)),
                ('payment_reference', models.CharField(max_length=50, null=True)),
                ('donation_amount', models.IntegerField(null=True)),
                ('donation_purpose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.Purpose')),
                ('payment_mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.PaymentMode')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='period_of_stay',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.Person'),
        ),
        migrations.AddField(
            model_name='phone',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.Person'),
        ),
    ]
