# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0005_auto_20171114_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reference_person',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
