# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0006_person_reference_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purpose',
            name='donation_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='donation_things',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='reference_person',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.Person'),
        ),
    ]
