# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0007_auto_20171117_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Receipt_number',
            new_name='receipt_number',
        ),
    ]
