# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0008_auto_20171117_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline_number', models.IntegerField(null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeInfo.Person')),
            ],
        ),
    ]
