# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0009_landline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landline',
            name='landline_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
