# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeInfo', '0010_auto_20171125_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='period_of_stay',
        ),
        migrations.AddField(
            model_name='person',
            name='period_of_stay_end',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='period_of_stay_start',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
